# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
    vmImage: 'macOS-10.15'
    
variables:
    scheme: 'myCurrencyExchange'
    sdk: 'iphoneos'
    configuration: 'Debug'

steps:
- task: Xcode@5
displayName: 'Running XCTest'
inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    packageApp: false
    xcWorkspacePath: 'AdvancedLogger.xcodeproj'
    destinationSimulators: 'iPhone 11'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true
    publishJUnitResults: 'build/reports/unit.xml'
