# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.15'

steps:
- task: Xcode@5
  inputs:
    actions: 'test' 'build'
    scheme: 'AdvancedLogger'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default'
