# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
    vmImage: 'macOS-10.15'

trigger:
    - master
    - develop

steps:
- task: Xcode@5
  inputs:
    actions: 'test'
    scheme: 'AdvancedLogger'
    sdk: 'macosx'
    configuration: 'Debug'
    xcWorkspacePath: 'AdvancedLogger.xcodeproj'
    signingOption: "auto"
    xcodeVersion: '11'
